name: Ejecución de pruebas con Ceedling

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
        with:
          ref: jf
              
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      
      - name: Install Ceedling
        run: gem install ceedling

      - name: Ejecutar pruebas con Ceedling
        run: |
          cd projects/lsel/ceedling
          ceedling test:all
      
